language: python

services:
  - docker

before_install:
  - cd exercise2/
  - docker build -t nvm-run -f run-app.Dockerfile .
  - docker build -t nvm-lint -f lint.Dockerfile .
  - docker build -t nvm-test -f test.Dockerfile .

jobs:
  include:
    - stage: lint
      name: "Code linting"
      script: docker container run nvm-lint
    - stage: test
      name: "Unit tests"
      script: docker container run nvm-test
