---
- name: 1. Get private IP from Replica
  shell: "hostname -I"
  register: replica_private_ip

- name: 2.Set Replica bind_address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address={{ replica_private_ip.stdout_lines[0] }}"

- name: 3.Set Replica log_bin
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#log_bin'
    line: "log_bin = /var/log/mysql/mysql-bin.log"

- name: 4.Set Replica binlog_do_db
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#binlog_do_db'
    line: "binlog_do_db={{ database_name }}"

- name: 5.Set Replica relay-log
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#relay-log'
    line: "relay-log=/var/log/mysql/mysql-relay-bin.log"

- name: 6.Configure Replica server ID
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#server-id'
    line: "server-id=2"
  notify:
    - restartMySQL

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: 7.Copy /home/ubuntu/permissions.sql
  template:
    src: sqlStatement.sql.j2
    dest: /home/ubuntu/permissions.sql
    owner: ubuntu
  tags:
    - replicapermissions

- name: 8.Copy dump file to Replica
  copy: 
    dest: /home/ubuntu/importScript.sql
    src: files/importScript.sql
    owner: ubuntu

- name: 9.Import DB from Master
  shell: "mysql {{ database_name }} < /home/ubuntu/importScript.sql"

- name: 10.Aplly permissions changes to Replica and Start Slave
  shell: "mysql {{ database_name }} < /home/ubuntu/permissions.sql"