---
- name: 1. Get private IP from Replica
  shell: "hostname -I"
  register: replica_private_ip

- name: 2.Set Replica bind_address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address={{ replica_private_ip.stdout_lines[0] }}"

- name: 3.Set Replica log_bin
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#log_bin'
    line: "log_bin = /var/log/mysql/mysql-bin.log"

- name: 4.Set Replica binlog_do_db
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#binlog_do_db'
    line: "binlog_do_db={{ database_name }}"

- name: 5.Set Replica relay-log
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#relay-log'
    line: "relay-log=/var/log/mysql/mysql-relay-bin.log"

- name: 6.Configure Replica server ID
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#server-id'
    line: "server-id=2"
  notify:
    - restartMySQL

- name: 7.Copy /home/ubuntu/permissions.sql
  copy: 
    content: "CHANGE MASTER TO MASTER_HOST='{{ master_private_ip }}',MASTER_USER='{{ replica_user }}',MASTER_PASSWORD='{{ replica_password }}',MASTER_LOG_FILE='mysql-bin.000001',MASTER_LOG_POS=107;"
    dest: /home/ubuntu/permissions.sql

- name: 8.Import DB from Master
  mysql_db:
    import: /home/ubuntu/importScript.sql

- name: 9.Aplly permissions changes to Replica
  shell: mysql {{ database_name }} < /home/ubuntu/permissions.sql

- name: 10.Start Replica
  mysql_replication:
    mode: stopslave