---
- name: 1. Get private IP from Master
  shell: "hostname -I"
  register: master_private_ip

- name: 2.Configure Master repplication
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address={{ master_private_ip.stdout_lines[0] }}"

- name: 3.Configure Master repplication
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#log_bin'
    line: "log_bin = /var/log/mysql/mysql-bin.log"

- name: 4.Configure Master repplication
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#binlog_do_db'
    line: "binlog_do_db={{ database_name }}"

- name: 5.Configure Master repplication
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#server-id'
    line: "server-id=1"
  notify:
    - restartMySQL

- name: 6.Copy SQL script to create users table
  copy:
    src: files/createTable.sql
    dest: /home/ubuntu/createTable.sql
    owner: ubuntu

- name: 7.Run script against database
  shell: mysql {{ database_name }} < /home/ubuntu/createTable.sql

- name: 8.Dump to a file
  mysql_db:
    state: dump
    name: all
    target: /home/ubuntu/importScript.sql

- name: 9.Copy dump file from master
  fetch: 
    flat: yes
    src: /home/ubuntu/importScript.sql
    dest: ./roles/mysql-replicas/files/importScript.sql
  tags: copyDump