---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common
- hosts: master
  become: yes
  gather_facts: yes
  roles:
    - mysql-master

- hosts: replicas
  become: yes
  gather_facts: yes
  roles:
    - mysql-replica