---
database_name: "nvmDB"
master_private_ip: "{{ hostvars[groups['master'][0]].private_ip }}"
mysql_root_pass: "{{ lookup('file', 'files/root.txt')}}"
replica_user: "replica_user" 
replica_password: "{{ lookup('file', 'files/replica.txt')}}"